### ISSUE TITLE
Buzzer 

### ISSUE THREAD

**Issue by DieterHolz** [Pi4J/pi4j-example-components#2]
BuzzerComponent 

Maybe we need a buzzer like this one
https://tinyurl.com/5d799e3f

Functions to provide
- [x] can play a tone 
- [x] can change the volume
- [x] can play a single note
- [x] can play a melody

Documents to create
- [x] A description of the principle operation
- [x] A layout of the wiring
- [x] A software component for control
- [x] An example application
- [x] Another product idea

Implementation in demoprojects
- [x]  Implemented in Theremin

**Comment by Mikscho** [comment]
@DieterHolz 
Don't we need a passive buzzer? as the active one will make a sound, as soon as it's powered?
This one would be recommended: https://tinyurl.com/35v9cdj6

**Comment by DieterHolz** [comment]
We need a buzzer that can change the volume (and still produce a "nice" sound).

Actually, I don't know if we have to use a passive or an active buzzer for that.

**Comment by Mikscho** [comment]
Yeah, i've read into it.
We can use one of them:
Buzzer1
https://www.berrybase.de/sensoren-module/audio-schall/ky-006-passives-buzzer-modul?c=89

Buzzer2
https://www.berrybase.de/sensoren-module/audio-schall/ky-012-aktives-buzzer-modul

While we vary with the input-Voltage, we can control the sound-volume
