### ISSUE TITLE
Order components for Theremin

### ISSUE THREAD

**Issue by RetoStutz** [Pi4J/pi4j-example-components#25]
Select and order all components needed for a Theremin

selected component:
Distance-Sensor: https://www.reichelt.com/ch/de/entwicklerboards-ultraschall-abstandssensor-hc-sr04-debo-sen-ultra-p161487.html?search=HC-SR04&&r=1

Buzzer: https://de.banggood.com/3_3-5V-Passive-Buzzer-Alarm-Module-p-985131.html?cur_warehouse=CN&rmmds=search

potentiometer: https://www.berrybase.de/bauelemente/passive-bauelemente/potentiometer/schiebepotis/schiebepotentiometer-mono-10k-937-500mw-tht-177-20-linear

LED strip: https://www.berrybase.de/sensoren-module/led/ws2812-13-neopixel/stripes/digitaler-led-rgb-neopixel-stripe-ip65-vergossen-60-leds/m-schwarze-leiterbahn-5m-rolle

on off switch: https://www.reichelt.com/ch/de/schiebeschalter-miniatur-loetanschluss-1x-um-t-215-p19975.html?&trstct=pos_0&nbc=1

required components
- [x] Buzzer
- [x] LED-Strip for frequency
- [x] Potentiometer
- [x] Distance-Sensor
- [x]  on / off switch

**Comment by DieterHolz** [comment]
an on/off-switch would be nice
