### ISSUE TITLE
Order all components for photobooth

### ISSUE THREAD

**Issue by RetoStutz** [Pi4J/pi4j-example-components#26]
Select and order all components needed for the Photobooth catalog

selected component:

Camera: https://www.reichelt.com/ch/de/raspberry-pi-kamera-5mp-inkl-stromversorgung-ov5647-rpi-jt-cam-5mp-p218887.html?&trstct=pos_2&nbc=1

Button for Trigger: https://de.banggood.com/5-Colors-LED-Light-60MM-Arcade-Video-Game-Player-Push-Button-Switch-p-934796.html?rmmds=product_topselling&cur_warehouse=CN&act_poa=POA224502&ID=513344

Servo Motor: https://www.berrybase.de/bauelemente/elektromagnetische-bauelemente/motoren-servos/sg92r-micro-servo?number=SG92R

Servo Motor: https://www.berrybase.de/bauelemente/elektromagnetische-bauelemente/motoren-servos/adafruit-standard-servo-towerpro-sg-5010?number=ADA155

Flash-light: is an LED strip

display: https://www.raspberrypi.com/products/raspberry-pi-touch-display/?resellerType=education

required components
- [x] Flash-light
- [x] Visualization of the countdown
- [x] remote control for trigger photo
- [x] Monitor for preview
- [x] Camera

**Comment by DieterHolz** [comment]
An idea how to include a servo motor

https://makersportal.com/blog/2020/3/21/raspberry-pi-servo-panning-camera?rq=camera
