### ISSUE TITLE
RGB LED Strip

### ISSUE THREAD

**Issue by DieterHolz** [Pi4J/pi4j-example-components#3]
Create a RGB LED Controller

selected component:
https://www.berrybase.de/sensoren-module/led/ws2812-13-neopixel/stripes/adafruit-neopixel-led-side-light-streifen-120-led-1m?c=2427

Functions to provide
- [x] Color of each LED can be set

Documents to create
- [x] A description of the principle operation
- [x] A layout of the wiring
- [x] A software component for control
- [x] An example application
- [x] Another product idea

Implementation in demoprojects
- [x]  Implemented in Photobooth

**Comment by Mikscho** [comment]
best one: https://www.berrybase.de/sensoren-module/led/ws2812-13-neopixel/stripes/digitaler-led-rgb-neopixel-stripe-ip65-vergossen-60-leds/m-schwarze-leiterbahn-5m-rolle

Here, each LED can be set on its own.
