### ISSUE TITLE
RGB LED Matrix

### ISSUE THREAD

**Issue by DieterHolz** [Pi4J/pi4j-example-components#4]
RGB LED Matrix

The matrix is realized with several LED strips placed next to each other. This reduces the required components

selected component:

Functions to provide
- [x] Each LED can be turned on/off
- [x] Color can be set for each LED

Documents to create
- [x] A description of the principle operation
- [x] A layout of the wiring
- [x] A software component for control
- [x] An example application
- [x] Another product idea

Implementation in demoprojects
- [x]  Implemented in Photobooth

**Comment by Mikscho** [comment]
Could be made with https://www.berrybase.de/sensoren-module/led/ws2812-13-neopixel/stripes/digitaler-led-rgb-neopixel-stripe-ip65-vergossen-60-leds/m-schwarze-leiterbahn-5m-rolle

You have to cut it, and solder some strips below each other.
Then, you can define a 2d array with the strips in the code, as the LED are still one serial strip.
