### ISSUE TITLE
Simplest Single Source GPIO on and off Example.

### ISSUE THREAD

**Issue by hurelhuyag** [Pi4J/pi4j-example-components#62]
This project is too bloated to understand as a beginner. I wanted to implement a simple GPIO on-and-off example. But in this project, every class tangled with each other. There is too much abstraction for an example project. This is no beginner-friendly project. 

When things go with Python, it is 3 lines of code. 

1. Import library, 
2. setup GPIO, 
3. .on() or .off() function.

Very simple, and understandable. But I don't like Python. It's not a good choice for long-term development.

Can we have a beginner-friendly single-source GPIO on-and-off example in the project?

**Comment by FDelporte** [comment]
Hi, indeed this project's use case is not the "simple getting started". But we have others for that:

* Single Java file with JBang: https://pi4j.com/examples/jbang/jbang_minimal_example/
* A bit more as a full Maven or Gradle project: https://pi4j.com/getting-started/minimal-example-application/
