### ISSUE TITLE
maven integration

### ISSUE THREAD

**Issue by razorne** [Pi4J/pi4j-example-components#63]
Hello, my question is very trivial. The project structure appears to be maven, but i cannot download this dependency from the central.
I just need the class used in https://pi4j.com/examples/components/lcddisplay/ without copying and pasting the raw class in my own code. Is this possible? Am i missing something? Thanks

**Comment by FDelporte** [comment]
Hi, this repository contains example implementations using Pi4J V2. So you are right, the code here is not available as a Maven library. Please check the [README.md here](https://github.com/Pi4J/pi4j-example-components/blob/main/README.md), or even more info on https://pi4j.com/examples/components/ how to use this code.

**Comment by razorne** [comment]
Hello, thank you for your response. I tried to copy and paste the code and use it this way, but unfortunately there seem to be problems with version i am using.

This example https://pi4j.com/examples/components/lcddisplay/ appears to use old version of pi4j where things were done in a different way than are today.

Anyway i am guessing that i can write some value to the LCD display, given the fact that it's just a device on an i2c bus. Right? All in all, maybe i can make it work without higher level code abstraction
